# Make sure to check the documentation at http://goreleaser.com
project_name: kairos-agent
builds:
  - ldflags:
      - -w -s -X "github.com/kairos-io/kairos/v2/internal/common.VERSION={{.Tag}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: '{{ .ProjectName }}'
archives:
  - format: binary
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
